[tools]
bun = "1.2.19"
deno = "latest"
go = "latest"
java = "liberica-21.0.6+10"
kotlin = "latest"
lua = "latest"
node = "lts"
"npm:@aku11i/phantom" = "latest"
"npm:@biomejs/biome" = "latest"
"npm:markdownlint-cli" = "latest"
"npm:markdownlint-cli2" = "latest"
"npm:neovim" = "latest"
"npm:textlint" = "latest"
ruby = "3.4.8"
rust = "stable"
shellcheck = "latest"
tree-sitter = "latest"

[hooks]
enter = "mise i -q"

[settings]
idiomatic_version_file_enable_tools = ["node"]
experimental = true

